-- Hardening: enforce same-family relationships and add lookup indexes.
-- No application behavior is changed; this only prevents cross-family references
-- and improves query performance.

-- Composite unique keys allow PostgreSQL to enforce that referenced records
-- belong to the same parent family.
CREATE UNIQUE INDEX IF NOT EXISTS t_filho_pai_id_uq
  ON public.t_filho(id_usuario_pai, id);

CREATE UNIQUE INDEX IF NOT EXISTS t_tarefa_pai_id_uq
  ON public.t_tarefa(id_usuario_pai, id);

CREATE UNIQUE INDEX IF NOT EXISTS t_vigencia_pai_id_uq
  ON public.t_vigencia(id_usuario_pai, id);

CREATE UNIQUE INDEX IF NOT EXISTS t_filho_tarefa_pai_id_uq
  ON public.t_filho_tarefa(id_usuario_pai, id);

-- Ensure an assignment can only combine child, task and validity
-- from the same family.
ALTER TABLE public.t_filho_tarefa
  ADD CONSTRAINT t_filho_tarefa_same_pai_filho_fk
  FOREIGN KEY (id_usuario_pai, id_filho)
  REFERENCES public.t_filho(id_usuario_pai, id)
  ON DELETE CASCADE;

ALTER TABLE public.t_filho_tarefa
  ADD CONSTRAINT t_filho_tarefa_same_pai_tarefa_fk
  FOREIGN KEY (id_usuario_pai, id_tarefa)
  REFERENCES public.t_tarefa(id_usuario_pai, id)
  ON DELETE CASCADE;

ALTER TABLE public.t_filho_tarefa
  ADD CONSTRAINT t_filho_tarefa_same_pai_vigencia_fk
  FOREIGN KEY (id_usuario_pai, id_vigencia)
  REFERENCES public.t_vigencia(id_usuario_pai, id)
  ON DELETE CASCADE;

-- Ensure an occurrence belongs to the same family as its assignment.
ALTER TABLE public.t_ocorrencia
  ADD CONSTRAINT t_ocorrencia_same_pai_assignment_fk
  FOREIGN KEY (id_usuario_pai, id_filho_tarefa)
  REFERENCES public.t_filho_tarefa(id_usuario_pai, id)
  ON DELETE CASCADE;

-- Frequently used owner/filter/join indexes.
CREATE INDEX IF NOT EXISTS t_filho_pai_idx
  ON public.t_filho(id_usuario_pai);

CREATE INDEX IF NOT EXISTS t_tarefa_pai_idx
  ON public.t_tarefa(id_usuario_pai);

CREATE INDEX IF NOT EXISTS t_vigencia_pai_idx
  ON public.t_vigencia(id_usuario_pai);

CREATE INDEX IF NOT EXISTS t_filho_tarefa_pai_idx
  ON public.t_filho_tarefa(id_usuario_pai);

CREATE INDEX IF NOT EXISTS t_filho_tarefa_filho_idx
  ON public.t_filho_tarefa(id_filho);

CREATE INDEX IF NOT EXISTS t_filho_tarefa_vigencia_idx
  ON public.t_filho_tarefa(id_vigencia);

CREATE INDEX IF NOT EXISTS t_ocorrencia_pai_idx
  ON public.t_ocorrencia(id_usuario_pai);

-- Public read-only access for a child's acompanhamento panel.
-- Additive migration: existing children and their IDs/data are untouched.
-- A row is created only when the parent explicitly enables public access.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.t_filho_acesso_publico (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario_pai bigint NOT NULL,
  id_filho bigint NOT NULL,
  token uuid NOT NULL DEFAULT gen_random_uuid(),
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT t_filho_acesso_publico_token_uq UNIQUE (token),
  CONSTRAINT t_filho_acesso_publico_pai_filho_uq UNIQUE (id_usuario_pai, id_filho),
  CONSTRAINT t_filho_acesso_publico_same_family_fk
    FOREIGN KEY (id_usuario_pai, id_filho)
    REFERENCES public.t_filho(id_usuario_pai, id)
    ON DELETE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.t_filho_acesso_publico TO authenticated;
GRANT ALL ON public.t_filho_acesso_publico TO service_role;

CREATE INDEX IF NOT EXISTS t_filho_acesso_publico_pai_idx
  ON public.t_filho_acesso_publico(id_usuario_pai);

CREATE INDEX IF NOT EXISTS t_filho_acesso_publico_filho_idx
  ON public.t_filho_acesso_publico(id_filho);

CREATE INDEX IF NOT EXISTS t_filho_acesso_publico_token_ativo_idx
  ON public.t_filho_acesso_publico(token)
  WHERE ativo = true;

ALTER TABLE public.t_filho_acesso_publico ENABLE ROW LEVEL SECURITY;

-- Only the authenticated parent who owns the child can manage its public link.
CREATE POLICY t_filho_acesso_publico_parent_select
ON public.t_filho_acesso_publico
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.t_usuario_pai p
    WHERE p.id = t_filho_acesso_publico.id_usuario_pai
      AND p.auth_user_id = auth.uid()
  )
);

CREATE POLICY t_filho_acesso_publico_parent_insert
ON public.t_filho_acesso_publico
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.t_usuario_pai p
    WHERE p.id = t_filho_acesso_publico.id_usuario_pai
      AND p.auth_user_id = auth.uid()
  )
  AND EXISTS (
    SELECT 1
    FROM public.t_filho f
    WHERE f.id = t_filho_acesso_publico.id_filho
      AND f.id_usuario_pai = t_filho_acesso_publico.id_usuario_pai
  )
);

CREATE POLICY t_filho_acesso_publico_parent_update
ON public.t_filho_acesso_publico
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.t_usuario_pai p
    WHERE p.id = t_filho_acesso_publico.id_usuario_pai
      AND p.auth_user_id = auth.uid()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.t_usuario_pai p
    WHERE p.id = t_filho_acesso_publico.id_usuario_pai
      AND p.auth_user_id = auth.uid()
  )
  AND EXISTS (
    SELECT 1
    FROM public.t_filho f
    WHERE f.id = t_filho_acesso_publico.id_filho
      AND f.id_usuario_pai = t_filho_acesso_publico.id_usuario_pai
  )
);

CREATE POLICY t_filho_acesso_publico_parent_delete
ON public.t_filho_acesso_publico
FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.t_usuario_pai p
    WHERE p.id = t_filho_acesso_publico.id_usuario_pai
      AND p.auth_user_id = auth.uid()
  )
);

-- No anon SELECT policy is intentionally created. Public visitors must never
-- read this table (or the family tables) directly. The public endpoint will
-- validate the token server-side and return only the allowed child data.

CREATE OR REPLACE FUNCTION public.touch_filho_acesso_publico_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_filho_acesso_publico_updated_at
ON public.t_filho_acesso_publico;

CREATE TRIGGER trg_touch_filho_acesso_publico_updated_at
BEFORE UPDATE ON public.t_filho_acesso_publico
FOR EACH ROW
EXECUTE FUNCTION public.touch_filho_acesso_publico_updated_at();

-- Authenticated management API for the child's public acompanhamento link.
-- The caller never supplies a parent id: it is always derived from auth.uid().

CREATE OR REPLACE FUNCTION public.gerar_acesso_publico_filho(p_id_filho bigint)
RETURNS TABLE(token uuid, ativo boolean)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_pai_id bigint;
BEGIN
  SELECT p.id
    INTO v_pai_id
  FROM public.t_usuario_pai p
  WHERE p.auth_user_id = auth.uid();

  IF v_pai_id IS NULL THEN
    RAISE EXCEPTION 'Responsável não encontrado';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.t_filho f
    WHERE f.id = p_id_filho
      AND f.id_usuario_pai = v_pai_id
  ) THEN
    RAISE EXCEPTION 'Filho não encontrado para este responsável';
  END IF;

  INSERT INTO public.t_filho_acesso_publico (id_usuario_pai, id_filho, ativo)
  VALUES (v_pai_id, p_id_filho, true)
  ON CONFLICT (id_usuario_pai, id_filho)
  DO UPDATE SET ativo = true, updated_at = now();

  RETURN QUERY
  SELECT a.token, a.ativo
  FROM public.t_filho_acesso_publico a
  WHERE a.id_usuario_pai = v_pai_id
    AND a.id_filho = p_id_filho;
END;
$$;

CREATE OR REPLACE FUNCTION public.regenerar_acesso_publico_filho(p_id_filho bigint)
RETURNS TABLE(token uuid, ativo boolean)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_pai_id bigint;
BEGIN
  SELECT p.id
    INTO v_pai_id
  FROM public.t_usuario_pai p
  WHERE p.auth_user_id = auth.uid();

  IF v_pai_id IS NULL THEN
    RAISE EXCEPTION 'Responsável não encontrado';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.t_filho f
    WHERE f.id = p_id_filho
      AND f.id_usuario_pai = v_pai_id
  ) THEN
    RAISE EXCEPTION 'Filho não encontrado para este responsável';
  END IF;

  INSERT INTO public.t_filho_acesso_publico (id_usuario_pai, id_filho, token, ativo)
  VALUES (v_pai_id, p_id_filho, gen_random_uuid(), true)
  ON CONFLICT (id_usuario_pai, id_filho)
  DO UPDATE SET token = gen_random_uuid(), ativo = true, updated_at = now();

  RETURN QUERY
  SELECT a.token, a.ativo
  FROM public.t_filho_acesso_publico a
  WHERE a.id_usuario_pai = v_pai_id
    AND a.id_filho = p_id_filho;
END;
$$;

CREATE OR REPLACE FUNCTION public.desativar_acesso_publico_filho(p_id_filho bigint)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_pai_id bigint;
  v_count integer;
BEGIN
  SELECT p.id
    INTO v_pai_id
  FROM public.t_usuario_pai p
  WHERE p.auth_user_id = auth.uid();

  IF v_pai_id IS NULL THEN
    RAISE EXCEPTION 'Responsável não encontrado';
  END IF;

  UPDATE public.t_filho_acesso_publico a
  SET ativo = false, updated_at = now()
  WHERE a.id_usuario_pai = v_pai_id
    AND a.id_filho = p_id_filho;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count > 0;
END;
$$;

CREATE OR REPLACE FUNCTION public.obter_acesso_publico_filho(p_id_filho bigint)
RETURNS TABLE(token uuid, ativo boolean)
LANGUAGE sql
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT a.token, a.ativo
  FROM public.t_filho_acesso_publico a
  JOIN public.t_usuario_pai p ON p.id = a.id_usuario_pai
  WHERE p.auth_user_id = auth.uid()
    AND a.id_filho = p_id_filho
    AND a.id_usuario_pai = p.id
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.gerar_acesso_publico_filho(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.regenerar_acesso_publico_filho(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.desativar_acesso_publico_filho(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.obter_acesso_publico_filho(bigint) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.gerar_acesso_publico_filho(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.regenerar_acesso_publico_filho(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.desativar_acesso_publico_filho(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.obter_acesso_publico_filho(bigint) TO authenticated;

-- Read-only public dashboard API. The bearer token resolves both parent and child
-- server-side and only a whitelisted JSON payload is returned.

CREATE OR REPLACE FUNCTION public.obter_painel_publico_filho(p_token uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_pai_id bigint;
  v_filho_id bigint;
  v_result jsonb;
BEGIN
  SELECT a.id_usuario_pai, a.id_filho
    INTO v_pai_id, v_filho_id
  FROM public.t_filho_acesso_publico a
  JOIN public.t_filho f
    ON f.id = a.id_filho
   AND f.id_usuario_pai = a.id_usuario_pai
  WHERE a.token = p_token
    AND a.ativo = true
  LIMIT 1;

  IF v_pai_id IS NULL OR v_filho_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT jsonb_build_object(
    'filho', jsonb_build_object(
      'nome', f.nome,
      'tem_mesada', COALESCE(f.tem_mesada_opcional, false) AND f.valor_mesada IS NOT NULL,
      'valor_mesada', f.valor_mesada
    ),
    'vigencias', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'id', v.id,
          'data_inicio', v.data_inicio,
          'data_fim', v.data_fim,
          'penalidade', v.penalidade,
          'qtd_ocorrencia', v.qtd_ocorrencia,
          'tipo_penalidade', v.tipo_penalidade,
          'valor_debito', v.valor_debito,
          'tarefas', COALESCE((
            SELECT jsonb_agg(
              jsonb_build_object(
                'id', ft.id,
                'nome', t.nome,
                'feito', ft.feito,
                'qtd_nao_fez', ft.qtd_nao_fez,
                'ocorrencias', COALESCE((
                  SELECT jsonb_agg(
                    jsonb_build_object(
                      'tipo', o.tipo,
                      'data', o.created_at
                    ) ORDER BY o.created_at DESC
                  )
                  FROM public.t_ocorrencia o
                  WHERE o.id_filho_tarefa = ft.id
                    AND o.id_usuario_pai = v_pai_id
                ), '[]'::jsonb)
              ) ORDER BY t.nome
            )
            FROM public.t_filho_tarefa ft
            JOIN public.t_tarefa t
              ON t.id = ft.id_tarefa
             AND t.id_usuario_pai = v_pai_id
            WHERE ft.id_vigencia = v.id
              AND ft.id_filho = v_filho_id
              AND ft.id_usuario_pai = v_pai_id
          ), '[]'::jsonb)
        )
        ORDER BY
          CASE
            WHEN now() BETWEEN v.data_inicio AND v.data_fim THEN 0
            WHEN now() < v.data_inicio THEN 1
            ELSE 2
          END,
          v.data_inicio DESC
      )
      FROM public.t_vigencia v
      WHERE v.id_usuario_pai = v_pai_id
        AND EXISTS (
          SELECT 1
          FROM public.t_filho_tarefa ft
          WHERE ft.id_vigencia = v.id
            AND ft.id_filho = v_filho_id
            AND ft.id_usuario_pai = v_pai_id
        )
    ), '[]'::jsonb),
    'atualizado_em', now()
  )
  INTO v_result
  FROM public.t_filho f
  WHERE f.id = v_filho_id
    AND f.id_usuario_pai = v_pai_id;

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.obter_painel_publico_filho(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.obter_painel_publico_filho(uuid) TO anon, authenticated;
