-- Public read-only access for a child's acompanhamento panel.
-- Additive migration: existing children and their IDs/data are untouched.
-- A row is created only when the parent explicitly enables public access.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.t_filho_acesso_publico (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario_pai bigint NOT NULL,
  id_filho bigint NOT NULL,
  token uuid NOT NULL DEFAULT gen_random_uuid(),
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT t_filho_acesso_publico_token_uq UNIQUE (token),
  CONSTRAINT t_filho_acesso_publico_pai_filho_uq UNIQUE (id_usuario_pai, id_filho),
  CONSTRAINT t_filho_acesso_publico_same_family_fk
    FOREIGN KEY (id_usuario_pai, id_filho)
    REFERENCES public.t_filho(id_usuario_pai, id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS t_filho_acesso_publico_pai_idx
  ON public.t_filho_acesso_publico(id_usuario_pai);

CREATE INDEX IF NOT EXISTS t_filho_acesso_publico_filho_idx
  ON public.t_filho_acesso_publico(id_filho);

CREATE INDEX IF NOT EXISTS t_filho_acesso_publico_token_ativo_idx
  ON public.t_filho_acesso_publico(token)
  WHERE ativo = true;

ALTER TABLE public.t_filho_acesso_publico ENABLE ROW LEVEL SECURITY;

-- Only the authenticated parent who owns the child can manage its public link.
CREATE POLICY t_filho_acesso_publico_parent_select
ON public.t_filho_acesso_publico
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.t_usuario_pai p
    WHERE p.id = t_filho_acesso_publico.id_usuario_pai
      AND p.auth_user_id = auth.uid()
  )
);

CREATE POLICY t_filho_acesso_publico_parent_insert
ON public.t_filho_acesso_publico
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.t_usuario_pai p
    WHERE p.id = t_filho_acesso_publico.id_usuario_pai
      AND p.auth_user_id = auth.uid()
  )
  AND EXISTS (
    SELECT 1
    FROM public.t_filho f
    WHERE f.id = t_filho_acesso_publico.id_filho
      AND f.id_usuario_pai = t_filho_acesso_publico.id_usuario_pai
  )
);

CREATE POLICY t_filho_acesso_publico_parent_update
ON public.t_filho_acesso_publico
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.t_usuario_pai p
    WHERE p.id = t_filho_acesso_publico.id_usuario_pai
      AND p.auth_user_id = auth.uid()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.t_usuario_pai p
    WHERE p.id = t_filho_acesso_publico.id_usuario_pai
      AND p.auth_user_id = auth.uid()
  )
  AND EXISTS (
    SELECT 1
    FROM public.t_filho f
    WHERE f.id = t_filho_acesso_publico.id_filho
      AND f.id_usuario_pai = t_filho_acesso_publico.id_usuario_pai
  )
);

CREATE POLICY t_filho_acesso_publico_parent_delete
ON public.t_filho_acesso_publico
FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.t_usuario_pai p
    WHERE p.id = t_filho_acesso_publico.id_usuario_pai
      AND p.auth_user_id = auth.uid()
  )
);

-- No anon SELECT policy is intentionally created. Public visitors must never
-- read this table (or the family tables) directly. The public endpoint will
-- validate the token server-side and return only the allowed child data.

CREATE OR REPLACE FUNCTION public.touch_filho_acesso_publico_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_filho_acesso_publico_updated_at
ON public.t_filho_acesso_publico;

CREATE TRIGGER trg_touch_filho_acesso_publico_updated_at
BEFORE UPDATE ON public.t_filho_acesso_publico
FOR EACH ROW
EXECUTE FUNCTION public.touch_filho_acesso_publico_updated_at();
