import { createFileRoute, redirect } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { AlertTriangle, BarChart3, CalendarDays, ThumbsDown, ThumbsUp, TrendingDown, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyState, PageHeader } from "@/components/PageHeader";
import { ResponsiveFilters } from "@/components/ResponsiveFilters";
import { Pick } from "@/components/Pick";
import { fmtVigencia, useFilhos, useOcorrencias, useTarefas, useVigencias } from "@/lib/db";
import { ocorrenciasPenalizadas } from "@/lib/penalidade";
import { compararVigencias, situacaoVigencia } from "@/components/VigenciaStatus";
import { reais, usaDesconto, valorDebitado } from "@/lib/mesada";

export const Route = createFileRoute("/_authenticated/dashboard")({
  beforeLoad: () => {
    throw redirect({ to: "/relatorio" });
  },
  head:()=>({meta:[{title:"Dashboard — Combinado"},{name:"description",content:"Visão resumida de Fez, Não fez, penalidades e descontos."}]}),
  component:DashboardPage,
});
function mesAno(data:string){return new Intl.DateTimeFormat("pt-BR",{month:"short",year:"2-digit",timeZone:"America/Sao_Paulo"}).format(new Date(data));}

function DashboardPage(){
 const {data:vigencias=[]}=useVigencias(),{data:filhos=[]}=useFilhos(),{data:tarefas=[]}=useTarefas(),{data:ocorrencias=[],isLoading}=useOcorrencias();
 const [f,setF]=useState({vig:"all",filho:"all"}),[filtro,setFiltro]=useState(f);
 const vigenciasOrdenadas=[...vigencias].sort(compararVigencias);
 const lista=useMemo(()=>ocorrencias.filter(o=>{const ft=o.t_filho_tarefa;return ft&&(filtro.vig==="all"||ft.id_vigencia===Number(filtro.vig))&&(filtro.filho==="all"||ft.id_filho===Number(filtro.filho));}),[ocorrencias,filtro]);
 const listaFez=lista.filter(o=>o.tipo==="FEZ"),listaNaoFez=lista.filter(o=>o.tipo!=="FEZ");
 const totalBonusValor=listaFez.reduce((s,o)=>s+Number(o.bonificacao_valor??0),0);
 const totalBonusEscritas=listaFez.filter(o=>o.bonificacao_tipo==="TEXTO"&&Boolean(o.bonificacao_descricao?.trim())).length;
 const totalSemBonus=listaFez.filter(o=>o.bonificacao_tipo===null).length;
 const penalizadas=useMemo(()=>ocorrenciasPenalizadas(listaNaoFez,vigencias),[listaNaoFez,vigencias]);
 const totalPenalidades=listaNaoFez.filter(o=>{const ft=o.t_filho_tarefa;if(!ft||!penalizadas.has(o.id))return false;const filho=filhos.find(x=>x.id===ft.id_filho),vigencia=vigencias.find(x=>x.id===ft.id_vigencia);return Boolean(filho&&vigencia&&!usaDesconto(filho,vigencia));}).length;
 const gruposMesada=new Map<string,{filhoId:number;vigenciaId:number;total:number}>();
 for(const o of listaNaoFez){const ft=o.t_filho_tarefa;if(!ft)continue;const filho=filhos.find(x=>x.id===ft.id_filho),vigencia=vigencias.find(x=>x.id===ft.id_vigencia);if(!filho||!vigencia||!usaDesconto(filho,vigencia))continue;const chave=`${ft.id_filho}:${ft.id_vigencia}`,atual=gruposMesada.get(chave)??{filhoId:ft.id_filho,vigenciaId:ft.id_vigencia,total:0};atual.total+=1;gruposMesada.set(chave,atual);}
 let totalDescontado=0;for(const grupo of gruposMesada.values()){const filho=filhos.find(x=>x.id===grupo.filhoId),vigencia=vigencias.find(x=>x.id===grupo.vigenciaId);if(filho&&vigencia)totalDescontado+=valorDebitado(filho,vigencia,grupo.total);}
 const porFilho=filhos.map(filho=>{const regs=lista.filter(o=>o.t_filho_tarefa?.id_filho===filho.id),fezRegs=regs.filter(o=>o.tipo==="FEZ"),fez=fezRegs.length,naoFezRegs=regs.filter(o=>o.tipo!=="FEZ");const bonusValor=fezRegs.reduce((s,o)=>s+Number(o.bonificacao_valor??0),0),bonusEscritas=fezRegs.filter(o=>o.bonificacao_tipo==="TEXTO"&&Boolean(o.bonificacao_descricao?.trim())).length,semBonus=fezRegs.filter(o=>o.bonificacao_tipo===null).length;const penalidades=naoFezRegs.filter(o=>{const ft=o.t_filho_tarefa,v=ft?vigencias.find(x=>x.id===ft.id_vigencia):undefined;return Boolean(ft&&v&&penalizadas.has(o.id)&&!usaDesconto(filho,v));}).length;let desconto=0;const porVigencia=new Map<number,number>();for(const o of naoFezRegs){const id=o.t_filho_tarefa?.id_vigencia;if(id)porVigencia.set(id,(porVigencia.get(id)??0)+1);}for(const [id,total] of porVigencia){const v=vigencias.find(x=>x.id===id);if(v&&usaDesconto(filho,v))desconto+=valorDebitado(filho,v,total);}const mesada=filho.tem_mesada_opcional===true&&filho.valor_mesada!==null?filho.valor_mesada:null,diferenca=mesada===null?null:Math.max(0,mesada-desconto);return{id:filho.id,nome:filho.nome,fez,naoFez:naoFezRegs.length,total:regs.length,penalidades,desconto,mesada,diferenca,bonusValor,bonusEscritas,semBonus};}).filter(x=>x.total>0).sort((a,b)=>b.total-a.total);
 const porTarefa=tarefas.map(tarefa=>{const regs=lista.filter(o=>o.t_filho_tarefa?.id_tarefa===tarefa.id);return{id:tarefa.id,nome:tarefa.nome,fez:regs.filter(o=>o.tipo==="FEZ").length,naoFez:regs.filter(o=>o.tipo!=="FEZ").length};}).filter(x=>x.fez+x.naoFez>0).sort((a,b)=>b.naoFez-a.naoFez).slice(0,5);const maxTarefa=Math.max(1,...porTarefa.map(x=>x.naoFez));
 const evolucaoMap=new Map<string,{fez:number;naoFez:number}>();for(const o of [...lista].sort((a,b)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime())){const chave=mesAno(o.created_at),atual=evolucaoMap.get(chave)??{fez:0,naoFez:0};if(o.tipo==="FEZ")atual.fez++;else atual.naoFez++;evolucaoMap.set(chave,atual);}const evolucao=[...evolucaoMap.entries()].slice(-6).map(([periodo,v])=>({periodo,...v}));
 return <><PageHeader title="Dashboard" description="Visão resumida de Fez, Não fez, penalidades e descontos." icon={<BarChart3 className="h-6 w-6"/>}/>
 <ResponsiveFilters desktopClassName="md:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]" onApply={()=>setFiltro(f)} renderFilters={()=>(
    <>
      <Pick label="Vigência" value={f.vig} onChange={vig=>setF({...f,vig})} allLabel="Todas" options={vigenciasOrdenadas.map(v=>({value:String(v.id),label:fmtVigencia(v),status:situacaoVigencia(v)}))}/>
      <Pick label="Filho" value={f.filho} onChange={filho=>setF({...f,filho})} allLabel="Todos" options={filhos.map(x=>({value:String(x.id),label:x.nome}))}/>
    </>
  )}/>
 {!isLoading&&lista.length===0?<EmptyState>Nenhum resultado encontrado para os filtros selecionados.</EmptyState>:<div className="space-y-6">
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Card><CardContent className="pt-5"><p className="flex items-center gap-1 text-xs font-medium text-muted-foreground"><ThumbsUp className="h-4 w-4 text-green-600"/> Total de “Fez”</p><p className="mt-1 text-3xl font-bold tabular-nums">{listaFez.length}</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-xs font-medium text-muted-foreground">Bonificações recebidas</p><div className="mt-2 space-y-1 text-sm"><p><span className="text-muted-foreground">Em dinheiro:</span> <strong className="tabular-nums text-foreground">{reais(totalBonusValor)}</strong></p><p><span className="text-muted-foreground">Escritas:</span> <strong className="text-foreground">{totalBonusEscritas}</strong></p><p><span className="text-muted-foreground">Fez sem bonificação:</span> <strong className="text-foreground">{totalSemBonus}</strong></p></div></CardContent></Card><Card><CardContent className="pt-5"><p className="flex items-center gap-1 text-xs font-medium text-muted-foreground"><ThumbsDown className="h-4 w-4 text-destructive"/> Total de “Não fez”</p><p className="mt-1 text-3xl font-bold tabular-nums">{listaNaoFez.length}</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-xs font-medium text-muted-foreground">Penalidades atingidas</p><p className="mt-1 text-3xl font-bold tabular-nums">{totalPenalidades}</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-xs font-medium text-muted-foreground">Desconto em mesadas</p><p className="mt-1 text-2xl font-bold tabular-nums">{reais(totalDescontado)}</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-xs font-medium text-muted-foreground">Filhos com resultados</p><p className="mt-1 text-3xl font-bold tabular-nums">{porFilho.length}</p></CardContent></Card></div>
 <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Users className="h-4 w-4"/> Resumo por filho</CardTitle></CardHeader><CardContent className="space-y-4">{porFilho.map(item=><div key={item.id} className="min-w-0 rounded-xl border p-4"><div className="flex items-center justify-between gap-3 border-b pb-3"><p className="min-w-0 truncate font-semibold">{item.nome}</p><span className="text-xs text-muted-foreground">{item.total} resultado(s)</span></div><div className="mt-3 grid gap-3 xl:grid-cols-3"><div className="rounded-lg bg-muted/40 p-3"><p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">Resultados</p><div className="mt-2 space-y-1.5 text-sm"><p className="flex items-center justify-between gap-3"><span className="flex items-center gap-1 text-green-700"><ThumbsUp className="h-4 w-4"/> Fez</span><strong>{item.fez}</strong></p><p className="flex items-center justify-between gap-3"><span className="flex items-center gap-1"><ThumbsDown className="h-4 w-4 text-destructive"/> Não fez</span><strong>{item.naoFez}</strong></p></div></div><div className="rounded-lg bg-green-50/70 p-3 dark:bg-green-950/20"><p className="text-[11px] font-semibold uppercase tracking-wide text-green-700 dark:text-green-300">Bonificações do Fez</p><div className="mt-2 space-y-1.5 text-sm"><p className="flex min-w-0 items-center justify-between gap-3"><span className="min-w-0">Em dinheiro</span><strong className="shrink-0 tabular-nums">{reais(item.bonusValor)}</strong></p><p className="flex items-center justify-between gap-3"><span>Escritas</span><strong>{item.bonusEscritas}</strong></p><p className="flex items-center justify-between gap-3"><span>Sem bonificação</span><strong>{item.semBonus}</strong></p></div></div><div className="rounded-lg bg-muted/40 p-3"><p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">{item.mesada!==null?"Mesada":"Penalidade"}</p>{item.mesada!==null?<div className="mt-2 space-y-1.5 text-sm"><p className="flex min-w-0 items-center justify-between gap-3"><span className="min-w-0">Valor</span><strong className="shrink-0 tabular-nums">{reais(item.mesada)}</strong></p><p className="flex min-w-0 items-center justify-between gap-3"><span className="min-w-0">Descontos</span><strong className="shrink-0 tabular-nums">{reais(item.desconto)}</strong></p><p className="flex min-w-0 items-center justify-between gap-3 border-t pt-1.5"><span className="min-w-0">Valor atual</span><strong className="shrink-0 tabular-nums">{reais(item.diferenca??0)}</strong></p></div>:<div className="mt-2 text-sm"><p className="flex items-center justify-between gap-3"><span>Penalidades atingidas</span><strong>{item.penalidades}</strong></p></div>}</div></div></div>)}</CardContent></Card>
 <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><AlertTriangle className="h-4 w-4"/> Tarefas com mais “Não fez”</CardTitle></CardHeader><CardContent className="space-y-4">{porTarefa.map(item=><div key={item.id}><div className="mb-1 flex items-center justify-between gap-3 text-sm"><span className="min-w-0 truncate font-medium">{item.nome}</span><span className="flex shrink-0 gap-2 tabular-nums"><span className="text-green-700">Fez: {item.fez}</span><span>Não fez: {item.naoFez}</span></span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${Math.max(6,(item.naoFez/maxTarefa)*100)}%`}}/></div></div>)}</CardContent></Card></div>
 <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><CalendarDays className="h-4 w-4"/> Evolução dos resultados</CardTitle></CardHeader><CardContent>{evolucao.length===0?<p className="text-sm text-muted-foreground">Sem dados para exibir.</p>:<div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{evolucao.map(item=><div key={item.periodo} className="rounded-lg border p-3 text-center"><p className="text-xs text-muted-foreground">{item.periodo}</p><p className="mt-2 text-sm font-semibold text-green-700">Fez: {item.fez}</p><p className="text-sm font-semibold">Não fez: {item.naoFez}</p></div>)}</div>}</CardContent></Card>
 {totalDescontado>0&&<p className="flex items-center gap-2 text-xs text-muted-foreground"><TrendingDown className="h-3.5 w-3.5"/> O total de desconto considera somente “Não fez” e nunca reduz a mesada abaixo de zero.</p>}
 </div>}</>;
}
