/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ExclusaoDeContaRouteImport } from './routes/exclusao-de-conta'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAtribuicoesRouteImport } from './routes/_authenticated/atribuicoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFilhosRouteImport } from './routes/_authenticated/filhos'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedLinkFilhosRouteImport } from './routes/_authenticated/link-filhos'
import { Route as AuthenticatedOcorrenciasRouteImport } from './routes/_authenticated/ocorrencias'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedVigenciasRouteImport } from './routes/_authenticated/vigencias'
import { Route as AcompanharTokenRouteImport } from './routes/acompanhar.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusaoDeContaRoute = ExclusaoDeContaRouteImport.update({
  id: '/exclusao-de-conta',
  path: '/exclusao-de-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtribuicoesRoute =
  AuthenticatedAtribuicoesRouteImport.update({
    id: '/atribuicoes',
    path: '/atribuicoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilhosRoute = AuthenticatedFilhosRouteImport.update({
  id: '/filhos',
  path: '/filhos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinkFilhosRoute = AuthenticatedLinkFilhosRouteImport.update({
  id: '/link-filhos',
  path: '/link-filhos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOcorrenciasRoute =
  AuthenticatedOcorrenciasRouteImport.update({
    id: '/ocorrencias',
    path: '/ocorrencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVigenciasRoute = AuthenticatedVigenciasRouteImport.update({
  id: '/vigencias',
  path: '/vigencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AcompanharTokenRoute = AcompanharTokenRouteImport.update({
  id: '/acompanhar/$token',
  path: '/acompanhar/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exclusao-de-conta': typeof ExclusaoDeContaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atribuicoes': typeof AuthenticatedAtribuicoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/filhos': typeof AuthenticatedFilhosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/link-filhos': typeof AuthenticatedLinkFilhosRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/vigencias': typeof AuthenticatedVigenciasRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exclusao-de-conta': typeof ExclusaoDeContaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atribuicoes': typeof AuthenticatedAtribuicoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/filhos': typeof AuthenticatedFilhosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/link-filhos': typeof AuthenticatedLinkFilhosRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/vigencias': typeof AuthenticatedVigenciasRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/exclusao-de-conta': typeof ExclusaoDeContaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/atribuicoes': typeof AuthenticatedAtribuicoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/filhos': typeof AuthenticatedFilhosRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/link-filhos': typeof AuthenticatedLinkFilhosRoute
  '/_authenticated/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/vigencias': typeof AuthenticatedVigenciasRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exclusao-de-conta'
    | '/politica-de-privacidade'
    | '/redefinir-senha'
    | '/admin'
    | '/atribuicoes'
    | '/dashboard'
    | '/filhos'
    | '/inicio'
    | '/link-filhos'
    | '/ocorrencias'
    | '/relatorio'
    | '/tarefas'
    | '/vigencias'
    | '/acompanhar/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exclusao-de-conta'
    | '/politica-de-privacidade'
    | '/redefinir-senha'
    | '/admin'
    | '/atribuicoes'
    | '/dashboard'
    | '/filhos'
    | '/inicio'
    | '/link-filhos'
    | '/ocorrencias'
    | '/relatorio'
    | '/tarefas'
    | '/vigencias'
    | '/acompanhar/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/exclusao-de-conta'
    | '/politica-de-privacidade'
    | '/redefinir-senha'
    | '/_authenticated/admin'
    | '/_authenticated/atribuicoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/filhos'
    | '/_authenticated/inicio'
    | '/_authenticated/link-filhos'
    | '/_authenticated/ocorrencias'
    | '/_authenticated/relatorio'
    | '/_authenticated/tarefas'
    | '/_authenticated/vigencias'
    | '/acompanhar/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ExclusaoDeContaRoute: typeof ExclusaoDeContaRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  AcompanharTokenRoute: typeof AcompanharTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusao-de-conta': {
      id: '/exclusao-de-conta'
      path: '/exclusao-de-conta'
      fullPath: '/exclusao-de-conta'
      preLoaderRoute: typeof ExclusaoDeContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atribuicoes': {
      id: '/_authenticated/atribuicoes'
      path: '/atribuicoes'
      fullPath: '/atribuicoes'
      preLoaderRoute: typeof AuthenticatedAtribuicoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/filhos': {
      id: '/_authenticated/filhos'
      path: '/filhos'
      fullPath: '/filhos'
      preLoaderRoute: typeof AuthenticatedFilhosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/link-filhos': {
      id: '/_authenticated/link-filhos'
      path: '/link-filhos'
      fullPath: '/link-filhos'
      preLoaderRoute: typeof AuthenticatedLinkFilhosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocorrencias': {
      id: '/_authenticated/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof AuthenticatedOcorrenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vigencias': {
      id: '/_authenticated/vigencias'
      path: '/vigencias'
      fullPath: '/vigencias'
      preLoaderRoute: typeof AuthenticatedVigenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/acompanhar/$token': {
      id: '/acompanhar/$token'
      path: '/acompanhar/$token'
      fullPath: '/acompanhar/$token'
      preLoaderRoute: typeof AcompanharTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAtribuicoesRoute: typeof AuthenticatedAtribuicoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFilhosRoute: typeof AuthenticatedFilhosRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedLinkFilhosRoute: typeof AuthenticatedLinkFilhosRoute
  AuthenticatedOcorrenciasRoute: typeof AuthenticatedOcorrenciasRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedVigenciasRoute: typeof AuthenticatedVigenciasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAtribuicoesRoute: AuthenticatedAtribuicoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFilhosRoute: AuthenticatedFilhosRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedLinkFilhosRoute: AuthenticatedLinkFilhosRoute,
  AuthenticatedOcorrenciasRoute: AuthenticatedOcorrenciasRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedVigenciasRoute: AuthenticatedVigenciasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ExclusaoDeContaRoute: ExclusaoDeContaRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  AcompanharTokenRoute: AcompanharTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
