-- 0037 - Infraestrutura de notificações push do app nativo.
-- Mantém tokens somente no backend e registra cada envio por aparelho/filho/dia
-- para evitar notificações duplicadas em caso de reexecução do agendamento.

create table if not exists public.t_push_dispositivo (
  id bigint generated by default as identity primary key,
  id_usuario_pai bigint not null references public.t_usuario_pai(id) on delete cascade,
  token text not null unique,
  plataforma text not null check (plataforma in ('android', 'ios')),
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_push_dispositivo_pai_ativo
  on public.t_push_dispositivo (id_usuario_pai, ativo);

alter table public.t_push_dispositivo enable row level security;

create table if not exists public.t_push_envio (
  id bigint generated by default as identity primary key,
  id_push_dispositivo bigint not null references public.t_push_dispositivo(id) on delete cascade,
  id_usuario_pai bigint not null references public.t_usuario_pai(id) on delete cascade,
  id_filho bigint not null references public.t_filho(id) on delete cascade,
  data_referencia date not null,
  qtd_pendencias integer not null check (qtd_pendencias > 0),
  created_at timestamptz not null default now(),
  constraint t_push_envio_unico_por_aparelho_filho_dia
    unique (id_push_dispositivo, id_filho, data_referencia)
);

create index if not exists idx_push_envio_pai_data
  on public.t_push_envio (id_usuario_pai, data_referencia);

alter table public.t_push_envio enable row level security;

comment on table public.t_push_dispositivo is
  'Dispositivos nativos registrados para receber notificações push do responsável.';

comment on table public.t_push_envio is
  'Controle idempotente dos pushes de pendência enviados por aparelho, filho e dia.';
